apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-vue-website
  labels:
    app: personal-vue-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-vue-website
  template:
    metadata:
      labels:
        app: personal-vue-website
    spec:
      containers:
      - name: personal-vue-website
        image: uncleboss12/personal-vue-webapp:v02
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
